# Generated by Django 4.2 on 2026-02-19 06:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NoteStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("note", models.CharField(max_length=8, unique=True)),
                ("total_attempts", models.PositiveIntegerField(default=0)),
                ("correct_count", models.PositiveIntegerField(default=0)),
                ("avg_confidence", models.FloatField(default=0.0)),
                ("last_seen", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["note"],
            },
        ),
        migrations.CreateModel(
            name="Session",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("started_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                ("level", models.PositiveSmallIntegerField(default=1)),
                ("total_exercises", models.PositiveIntegerField(default=0)),
                ("correct_count", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="Exercise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "part",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "Partie 1 — Écoute"), (2, "Partie 2 — Dessin")],
                        default=1,
                    ),
                ),
                ("note_displayed", models.CharField(max_length=8)),
                ("note_answered", models.CharField(blank=True, max_length=8)),
                ("correct", models.BooleanField(default=False)),
                ("confidence", models.FloatField(default=0.0)),
                ("attempts", models.PositiveSmallIntegerField(default=1)),
                ("response_time_ms", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exercises",
                        to="exercises.session",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
